#!/usr/bin/env python3
"""nomenclature_C.py — Catalogue composants vehicule biplace (scenario C)"""

CATEGORIE = "Scenario C - Milieu ferme"
VERSION = "0.1"

COMPOSANTS = [
    {"nom": "Chassis tubulaire acier", "sous_systeme": "Structure",
     "quantite": 1, "prix_unitaire": 1800, "fournisseur": "Atelier metallique local",
     "part_qc_pct": 90},
    {"nom": "Panneaux carrosserie composites", "sous_systeme": "Structure",
     "quantite": 1, "prix_unitaire": 3200, "fournisseur": "Composite Quebec",
     "part_qc_pct": 80},
    {"nom": "Cadre portes et ouvrants", "sous_systeme": "Structure",
     "quantite": 1, "prix_unitaire": 900, "fournisseur": "(a identifier)",
     "part_qc_pct": 70},
    {"nom": "Plancher aluminium", "sous_systeme": "Structure",
     "quantite": 1, "prix_unitaire": 450, "fournisseur": "(a identifier)",
     "part_qc_pct": 60},
    {"nom": "Sieges (paire)", "sous_systeme": "Interieur",
     "quantite": 1, "prix_unitaire": 600, "fournisseur": "(a identifier)",
     "part_qc_pct": 50},
    {"nom": "Pare-brise et vitres", "sous_systeme": "Interieur",
     "quantite": 1, "prix_unitaire": 700, "fournisseur": "(a identifier)",
     "part_qc_pct": 40},
    {"nom": "Tableau de bord", "sous_systeme": "Interieur",
     "quantite": 1, "prix_unitaire": 800, "fournisseur": "(a identifier)",
     "part_qc_pct": 60},
    {"nom": "Moteur brushless 8 kW", "sous_systeme": "Propulsion",
     "quantite": 1, "prix_unitaire": 1200, "fournisseur": "FTEX ou import",
     "part_qc_pct": 30},
    {"nom": "Controleur moteur", "sous_systeme": "Propulsion",
     "quantite": 1, "prix_unitaire": 600, "fournisseur": "(a identifier)",
     "part_qc_pct": 20},
    {"nom": "Reducteur / transmission", "sous_systeme": "Propulsion",
     "quantite": 1, "prix_unitaire": 800, "fournisseur": "(a identifier)",
     "part_qc_pct": 40},
    {"nom": "Arbre de transmission", "sous_systeme": "Propulsion",
     "quantite": 1, "prix_unitaire": 400, "fournisseur": "Atelier local",
     "part_qc_pct": 80},
    {"nom": "Cellules LFP 10 kWh", "sous_systeme": "Batterie",
     "quantite": 1, "prix_unitaire": 1100, "fournisseur": "Import",
     "part_qc_pct": 5},
    {"nom": "BMS", "sous_systeme": "Batterie",
     "quantite": 1, "prix_unitaire": 400, "fournisseur": "Import",
     "part_qc_pct": 10},
    {"nom": "Boitier batterie", "sous_systeme": "Batterie",
     "quantite": 1, "prix_unitaire": 500, "fournisseur": "Atelier local",
     "part_qc_pct": 70},
    {"nom": "Assemblage pack batterie", "sous_systeme": "Batterie",
     "quantite": 1, "prix_unitaire": 800, "fournisseur": "SysNergie",
     "part_qc_pct": 100},
    {"nom": "Chargeur embarque 3 kW", "sous_systeme": "Electrique",
     "quantite": 1, "prix_unitaire": 400, "fournisseur": "Import",
     "part_qc_pct": 15},
    {"nom": "Convertisseur DC/DC", "sous_systeme": "Electrique",
     "quantite": 1, "prix_unitaire": 200, "fournisseur": "Import",
     "part_qc_pct": 15},
    {"nom": "Cablage HT", "sous_systeme": "Electrique",
     "quantite": 1, "prix_unitaire": 300, "fournisseur": "Atelier local",
     "part_qc_pct": 70},
    {"nom": "Eclairage", "sous_systeme": "Electrique",
     "quantite": 1, "prix_unitaire": 350, "fournisseur": "(a identifier)",
     "part_qc_pct": 30},
    {"nom": "Direction", "sous_systeme": "Mecanique",
     "quantite": 1, "prix_unitaire": 450, "fournisseur": "(a identifier)",
     "part_qc_pct": 20},
    {"nom": "Suspension avant", "sous_systeme": "Mecanique",
     "quantite": 2, "prix_unitaire": 250, "fournisseur": "(a identifier)",
     "part_qc_pct": 20},
    {"nom": "Suspension arriere", "sous_systeme": "Mecanique",
     "quantite": 2, "prix_unitaire": 220, "fournisseur": "(a identifier)",
     "part_qc_pct": 20},
    {"nom": "Freins a disque (4)", "sous_systeme": "Mecanique",
     "quantite": 1, "prix_unitaire": 600, "fournisseur": "(a identifier)",
     "part_qc_pct": 25},
    {"nom": "Roues et pneus (4)", "sous_systeme": "Mecanique",
     "quantite": 4, "prix_unitaire": 180, "fournisseur": "Import",
     "part_qc_pct": 15},
    {"nom": "Frein de stationnement", "sous_systeme": "Mecanique",
     "quantite": 1, "prix_unitaire": 150, "fournisseur": "(a identifier)",
     "part_qc_pct": 40},
    {"nom": "Ceintures (paire)", "sous_systeme": "Securite",
     "quantite": 1, "prix_unitaire": 250, "fournisseur": "Import",
     "part_qc_pct": 10},
    {"nom": "Arceaux protection", "sous_systeme": "Securite",
     "quantite": 1, "prix_unitaire": 400, "fournisseur": "Atelier local",
     "part_qc_pct": 90},
    {"nom": "Coupe-circuit urgence", "sous_systeme": "Securite",
     "quantite": 1, "prix_unitaire": 100, "fournisseur": "Import",
     "part_qc_pct": 20},
    {"nom": "Klaxon", "sous_systeme": "Securite",
     "quantite": 1, "prix_unitaire": 80, "fournisseur": "Import",
     "part_qc_pct": 20},
    {"nom": "Peinture et finition", "sous_systeme": "Finition",
     "quantite": 1, "prix_unitaire": 500, "fournisseur": "Atelier local",
     "part_qc_pct": 80},
    {"nom": "Isolation", "sous_systeme": "Finition",
     "quantite": 1, "prix_unitaire": 300, "fournisseur": "(a identifier)",
     "part_qc_pct": 60},
    {"nom": "Chauffage habitacle", "sous_systeme": "Finition",
     "quantite": 1, "prix_unitaire": 250, "fournisseur": "(a identifier)",
     "part_qc_pct": 40},
    {"nom": "Main-d'oeuvre assemblage", "sous_systeme": "Assemblage",
     "quantite": 1, "prix_unitaire": 4500, "fournisseur": "Atelier Quebec",
     "part_qc_pct": 100},
    {"nom": "Ingenierie et integration", "sous_systeme": "Assemblage",
     "quantite": 1, "prix_unitaire": 6000, "fournisseur": "Ingenieur Quebec",
     "part_qc_pct": 100},
    {"nom": "Essais et validation", "sous_systeme": "Assemblage",
     "quantite": 1, "prix_unitaire": 1500, "fournisseur": "Interne",
     "part_qc_pct": 100},
]

VOLUME_CIBLE = 10
MARGE_UNITAIRE_PCT = 25
